name: bak8
version: git
summary: Rotational backup system for workstation users
description: |
  Bak8 is a rotational backup system focused on providing workstation users with easily accessible daily backups of their home directories.

  Backups can be configured to be archived, encrypted, and securely synchronized across multiple devices and cloud storage providers.


base: core24
confinement: classic

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]
  armhf:
    build-on: [amd64, armhf]
    build-for: [armhf]

parts:
  bak:
    plugin: rust
    source: ./packages/bak
    build-attributes:
      - enable-patchelf
  bak8:
      plugin: rust
      source: ./packages/bak8
      build-attributes:
        - enable-patchelf


apps:
  bak:
    command: bin/bak
  bak8:
    command: bin/bak8
