name: sourcetrait_backup
version: git
summary: Rotational backup system for workstation users
description: |
  SourceTrait Backup is a rotational backup system focused on providing workstation users with easily accessible daily backups of their home directories.

  Backups can be configured to be archived, encrypted, and securely synchronized across multiple devices and cloud storage providers.


base: core24
confinement: classic

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]
  armhf:
    build-on: [amd64, armhf]
    build-for: [armhf]

parts:
  sourcetrait_backup:
    plugin: rust
    source: .
    build-attributes:
      - enable-patchelf
    stage-packages:
      - rsync
      - tar
      - xz-utils
      - gpg
      - ssh

apps:
  sourcetrait_backup:
    command: sourcetrait_backup
  bak:
    command: bak
